In [1]:
list = ([1,2,3],[4,5,6])

In [2]:
import torch

In [3]:
x = torch.Tensor(list)

In [4]:
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
import numpy as np

In [7]:
list_numpy = np.array([[1,2,3],[4,5,6]])

In [8]:
xx = torch.Tensor(list_numpy)

In [9]:
print(xx)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [11]:
yy = torch.Tensor(np.array([[7,8,9],[1,2,3]]))

In [12]:
print(yy)

tensor([[7., 8., 9.],
        [1., 2., 3.]])
