In [4]:
import torch
import numpy as np

In [7]:
x = torch.Tensor(np.array([[1,2,3],[4,5,6],[7,8,9]]))

In [10]:
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [12]:
print(type(x))

<class 'torch.Tensor'>


In [8]:
x_back2list = x.tolist()

In [9]:
print(x_back2list)

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]


In [11]:
print(type(x_back2list))

<class 'list'>


In [13]:
x_back2numpy = x.numpy()

In [14]:
print(x_back2numpy)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [15]:
print(type(x_back2numpy))

<class 'numpy.ndarray'>
